---
title: "Matrix Factorization"
output: html_document
---


```{r gp, echo=F}
library(DiagrammeR)
nodes = create_nodes(    
  nodes = c('EPCA', 'PCA', 'FA', 'SVD', 'NMF', 'DPCA', 'LDA','PLSI', 'km'),
  label = c('Exponential\nPCA', 'PCA', 'FA', 'SVD', 'NMF', 'Discrete\nPCA', 'LDA', 'PLSI', 'K-means'),
  # type = 'a',
  # value = 1,
  style = 'filled',
  shape = 'circle',
  fixedsize=T,
  distortion='',
  color='#8B000040',
  fillcolor='papayawhip',
  fixedsize='',
  fontcolor='darkred',
  fontname='Roboto',
  fontsize=6,
  height='',
  penwidth='',
  peripheries='',
  sides='',
  tooltip='',
  width='',
  x='',
  y='')

edges = create_edges(
  from = c('EPCA', 'EPCA', 'DPCA', 'LDA', 'NMF', 'LDA', 'SVD'),
  to =   c('DPCA', 'PCA', 'LDA', 'NMF', 'PLSI', 'PLSI', 'PCA'),
  # rel = c('a'),
  arrowhead='dot',
  arrowsize='.5',
  arrowtail='',
  color='#FA8072BF',
  dir=c('none', 'none', '', '', 'none'),
  fontcolor='',
  fontname='',
  fontsize='',
  headport='',
  label='',
  minlen='',
  penwidth='2',
  tailport='',
  tooltip=c('', '', '', 'NMF w/ prior', 'PLSI &equiv; NMF with additional constraints on X', 'PLSI is the map estimate of LDA', 'The result of SVD can construct the covariance matrix PCA works on. See SE references')
)

# save(file='')
render_graph(create_graph(nodes_df = nodes, edges_df = edges, graph_name=''), height = 1000, width = 750)
```


## Connections to 

Hover over the links for details on *some* connections (i.e. not all edges have details).  Dots indicate 'special cases of' the parent node. Undirected connections suggest equivalence (&equiv; on hover) or a more complex relationship (usually for more general/more complex models).  Note this is for a quick reference, not an exhaustive one.

## Overview

Most matrix factorization techniques can be twisted from one to the other, such that this could essentially be a highly interconnected circular graph.


$$X \approx UV'$$
The observed data matrix $X$ is approximately equal to some function of the 'factors' $U$, and $V$, possibly weighted (all use equal weights), and generalizing further to include some link function i.e., $f(UV')$ (I only note EPCA here). 


## Labels

PCA: principal compenents analysis
Exponential PCA: exponential principal compenents analysis
Discrete CA: Discrete principal compenents analysis
FA: 'factor analysis'
SVD: singular value decomposition
LDA: latent dirichlet allocation
NMF: non-negative matrix factorization
PLSI: also as PLSA, probabilistic latent semantic analysis
K-means: k-means cluster approach

## References

Singh & Gordon (2008) A Unified View of Matrix Factorization Models.

#### Stack Exchange

PCA-SVD: [1](http://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca), [2](http://math.stackexchange.com/questions/3869/what-is-the-intuitive-relationship-between-svd-and-pca)